# Generated by Django 4.1.5 on 2023-01-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='fecharendida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
