# Generated by Django 4.1.5 on 2023-01-23 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Materias', '0002_alter_materias_fecharendida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='usuario',
        ),
    ]
